trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Terraform
  displayName: 'Terraform Job'
  steps:
  - task: HashiCorpTerraformToolInstaller@0.12.0
    inputs:
      terraformVersion: '0.14.7'

  - script: |
      terraform init
      terraform plan -out=tfplan
    displayName: 'Terraform Init and Plan'

  - script: terraform apply tfplan
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
